<a href="https://colab.research.google.com/github/sricharangk/SimpleLinearRegression/blob/master/multiplelinearregression.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [148]:
!ls

50_Startups.csv  Salary_Data.csv  sample_data


In [0]:
##import necessary libraries
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [0]:
#import the csv file 
dataset = pd.read_csv('50_Startups.csv')
#make your datasets ready
X = dataset.iloc[:, :-1]
y = dataset.iloc[:,4] 

In [151]:
#look at the dataset of independent features in the data set
X.head()


R&D Spend  Administration  Marketing Spend       State
0  165349.20       136897.80        471784.10    New York
1  162597.70       151377.59        443898.53  California
2  153441.51       101145.55        407934.54     Florida
3  144372.41       118671.85        383199.62    New York
4  142107.34        91391.77        366168.42     Florida

In [152]:
#look at the data of dependent variables
print(y.head())


0    192261.83
1    191792.06
2    191050.39
3    182901.99
4    166187.94
Name: Profit, dtype: float64


In [0]:
X = X.values
y = y.values

In [154]:
#to deal with categorical columns(here "State") in the data import sklearn preprocessing library
#use one hotencodi
from sklearn.preprocessing import LabelEncoder,OneHotEncoder
labelencoder = LabelEncoder()
X[:,3] = labelencoder.fit_transform(X[:,3])
onehotencoder = OneHotEncoder(categorical_features = [3])
X = onehotencoder.fit_transform(X).toarray()

/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:371: FutureWarning: The handling of integer data will change in version 0.22. Currently, the categories are determined based on the range [0, max(values)], while in the future they will be determined based on the unique values.
If you want the future behaviour and silence this warning, you can specify "categories='auto'".
In case you used a LabelEncoder before this OneHotEncoder to convert the categories to integers, then you can now use the OneHotEncoder directly.
  warnings.warn(msg, FutureWarning)
/usr/local/lib/python3.6/dist-packages/sklearn/preprocessing/_encoders.py:392: DeprecationWarning: The 'categorical_features' keyword is deprecated in version 0.20 and will be removed in 0.22. You can use the ColumnTransformer instead.
  "use the ColumnTransformer instead.", DeprecationWarning)


In [155]:
pd.DataFrame(X).head()

0    1    2          3          4          5
0  0.0  0.0  1.0  165349.20  136897.80  471784.10
1  1.0  0.0  0.0  162597.70  151377.59  443898.53
2  0.0  1.0  0.0  153441.51  101145.55  407934.54
3  0.0  0.0  1.0  144372.41  118671.85  383199.62
4  0.0  1.0  0.0  142107.34   91391.77  366168.42

In [0]:
#using sklearn library split the data into train and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 1/5, random_state = 0)

In [0]:
#import linearRegression model
from sklearn.linear_model import LinearRegression


In [158]:
#create an object to initialise the model
regressor = LinearRegression()
regressor.fit(X_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None,
         normalize=False)

$y = m_1x_1+m_2x_2....m_nx_n+ b$

$ m_1,m_2,m_3....m_n \>are \>coeffecients$

$b \>is \>intercept$

In [159]:
#get to know the intercetpts
regressor.intercept_

42467.52924853204

In [160]:
#get to know the coefficients
regressor.coef_

array([ 8.66383692e+01, -8.72645791e+02,  7.86007422e+02,  7.73467193e-01,
        3.28845975e-02,  3.66100259e-02])

In [0]:
y_train_For_test = regressor.predict(X_train)

In [162]:
y_train

array([ 96778.92,  96479.51, 105733.54,  96712.8 , 124266.9 , 155752.6 ,
       132602.65,  64926.08,  35673.41, 101004.64, 129917.04,  99937.59,
        97427.84, 126992.93,  71498.49, 118474.03,  69758.98, 152211.77,
       134307.35, 107404.34, 156991.12, 125370.37,  78239.91,  14681.4 ,
       191792.06, 141585.52,  89949.14, 108552.04, 156122.51, 108733.99,
        90708.19, 111313.02, 122776.86, 149759.96,  81005.76,  49490.75,
       182901.99, 192261.83,  42559.73,  65200.33])

In [163]:
y_train_For_test

array([ 95764.42320496,  89164.62849778, 109506.72329085,  91366.2188941 ,
       127111.48666647, 159019.04337115, 148905.98812541,  48179.60744027,
        45374.34722506, 102951.95967979, 145449.631784  ,  96684.71387297,
        97535.35761938, 116571.15139254,  69421.13311311, 116212.62095134,
        60736.5326761 , 152787.95464279, 127413.0337311 , 102210.16391826,
       161822.72264072, 131583.61511492,  75019.09161336,  48054.91969392,
       189547.28196895, 127528.92248423,  85540.50570954, 111255.82514049,
       156191.10124354, 108464.25100332,  75306.81185049, 119915.38726756,
       115144.58914953, 152688.9067796 ,  81513.47163491,  57298.28613019,
       172852.2833664 , 192919.57537466,  47007.62737748,  65835.99435875])

In [164]:
from sklearn.metrics import mean_squared_error
error_train = mean_squared_error(y_train_For_test, y_train)
error_train

81571001.8007737

In [165]:
y_pred = regressor.predict(X_test) 
error_test = mean_squared_error(y_test, y_pred)
error_test

83502864.03256583